### ISSUE TITLE
Content of link box

### ISSUE THREAD

**Issue by justlucdewit** [justlucdewit/41A-portfolios#2]
op de homepagina hebben we boxes met de namen staan, als je hier op klikt ga je naar je eigen sub pagina, hoe willen we de boxes vullen?

-persoonlijke fotos?
-een persoonlijke text?

bespreek hier

**Comment by ErayPack** [comment]
yanee

**Comment by Ponyprinses** [comment]
Beiden, een foto rechts en de tekst links of andersom.

**Comment by jolospongebob** [comment]
gewoon klasse foto's
of willen we nog een grote klasse foto maken voor de site

**Comment by Ponyprinses** [comment]
> gewoon klasse foto's
> of willen we nog een grote klasse foto maken voor de site
Ik stel voor gewoon dezelfde foto te gebruiken als op onze school pasjes

**Comment by jolospongebob** [comment]
dat is klasse foto
