### ISSUE TITLE
volgorde link boxes

### ISSUE THREAD

**Issue by justlucdewit** [justlucdewit/41A-portfolios#3]
hoe willen we de volgoorde van de link boxes bepalen?
als je onderaan staat word je minder snel aangeklikt

-alphabetisch?
-groote website?
-aantal commits?
-mooiheid website?

**Comment by Ponyprinses** [comment]
Ik denk dat we het beste gewoon koud alphabetish of groote website moeten doen, aantal commits zecht niet altijd alles over hoe veel er gedaan is en mooiheid is subjectief en daarnaast hebben we een standaard stylesheet.
